name: 6b6tLogin
version: '${version}'
main: com.blbilink.blbilogin.BlbiLogin
api-version: '1.20'
folia-supported: true
depend:
  - blbiLibrary
softdepend:
  - floodgate
commands:
  login:
    description: "使玩家进行登录"
    usage: /login <password>
    aliases: [l]
  register:
    description: "使玩家进行注册"
    usage: /register <password>
    aliases: [ reg ]
  blbilogin:
    description: "插件主命令"
    usage: /blbilogin <args>
  resetpassword:
    description: "重置密码"
    aliases:
      - resetpasswd
      - resetpass
      - resetpw
  stats:
    description: "查看服务器统计"
    usage: /stats
  tpa:
    description: "请求传送到其他玩家"
    usage: /tpa <player>
  tpahere:
    description: "请求其他玩家传送到你"
    usage: /tpahere <player>
  tpacancel:
    description: "取消传送请求"
    usage: /tpacancel
  tpadecline:
    description: "拒绝传送请求"
    usage: /tpadecline
  vanish:
    description: "隐身切换"
    usage: /vanish
