name: blbiLogin
version: '${version}'
main: com.blbilink.blbilogin.BlbiLogin
api-version: '1.20.6'

commands:
  login:
    description: "使玩家进行登录"
    usage: /login <password>
    aliases: [l]
  register:
    description: "使玩家进行注册"
    usage: /register <password>
    aliases: [ reg ]
  blbilogin:
    description: "插件主命令"
    usage: /blbilogin <args>
  resetpassword:
    description: "重置密码"
    aliases:
      - resetpasswd
      - resetpass
      - resetpw
