name: blbiLogin
version: '${version}'
main: com.blbilink.blbilogin.BlbiLogin
api-version: '1.21'
commands:
  login:
    description: "使玩家进行登录"
    usage: /login <password>
    aliases: [l]
  register:
    description: "使玩家进行注册"
    usage: /register <password>
    aliases: [ reg ]