name: Gradle Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all tags and branches

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Verify local dependencies
        run: |
          if [ -d "libs" ] && [ "$(ls -A libs)" ]; then
            echo "Local dependencies found in libs directory"
          else
            echo "Warning: libs directory is empty or does not exist. Make sure to commit your local JAR files."
            mkdir -p libs
          fi

      - name: Build with Gradle Wrapper
        run: |
          chmod +x ./gradlew
          ./gradlew build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: plugin
          path: build/libs/*.jar
